---
title: "PoliceStat Biweekly Reporting"
author: "April Welch"
email: "April.Welch@baltimorecity.gov"
output:
  html_notebook:
    code_folding: hide
    fig_height: 5
    fig_width: 10
    toc: yes
    toc_depth: 2
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = T, echo = T, message = FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = T, 
                      warning = F, 
                      message = F, 
                      include = T,
                      fig.width = 6,
                      fig.height = 3)
```

```{r libraries}
library(tidyverse)
library(RSocrata)
library(RcppRoll)
library(ggiteam)
#library(staplr)
library(scales)
library(lubridate)
library(rgdal)

#library(tidyverse)
#library(RSocrata)
#library(sp)
library(leaflet)
library(RODBC)
library(htmltools)
#library(rgdal)
#library(geojsonsf)
library(lubridate)
#library(leaflet.extras)
#library(mapview)
library(dplyr)

library(suncalc) # for sunrise and sunset times
#source("../src/functions.R")
```

```{r load_data}
#query <- paste0("https://data.baltimorecity.gov/resource/wsfq-mvij.json?$where=",
#                "(Description like 'HOMICIDE' OR ",
 #               "Description like 'SHOOTING' OR ", 
  #              "Description like 'AGG. ASSAULT' OR ",
   #             "contains(Description, 'ROBBERY')) AND ",
    #            "date_extract_y(crimedate) in(2020)")

df <- violent_crime
```


```{r}
df <- df %>% 
  filter(!is.na(latitude)) %>%
  mutate(crimedate = as.Date(crimedate),
         longitude = as.numeric(longitude),
         latitude = as.numeric(latitude),
         description = ifelse(grepl("ROBBERY", description), 
                              "ROBBERY", description))

last_date <- max(df$crimedate)
```


```{r fig.height = 8, fig.width = 16}
df %>%
  filter(crimedate>= '2021-01-01') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  count(description, crime_day, crime_hour) %>%
  group_by(description) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_day, crime_hour, fill = pct)) +
  facet_grid(cols = vars(description)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_day, crime_hour, label = n), size = 2) +
  scale_fill_continuous(type = "viridis", 
                        labels = percent,
                        name = "% of Daily Events") +
  theme_iteam_google_docs() +
  scale_x_continuous(breaks = seq(1,7,1)) +
  ggtitle(paste0("Records since ", min(df$crimedate))) +
  labs(title = "",
       y = "Hour of Day",
       x = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime, Data from ", min(df$crimedate),
                        " to ", max(df$crimedate)))
```
```{r fig.width = 8, fig.height = 4}
df %>%
  filter(description %in% c("ROBBERY"),
         crimedate>= '2021-01-01') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("ROBBERIES\nsince 2021-01-01")) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData from 2021-01-01",
                        " to ", max(df$crimedate))) 
```
```{r fig.width = 8, fig.height = 4}
df %>%
  filter(description %in% c("ROBBERY"),
         crimedate< '2021-01-01',
         crimedate>= '2019-01-01') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("ROBBERIES\n2019-2020")) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("2019-2020 Part1 Crime\nData",
                        " to ", max(df$crimedate)))

```

```{r fig.width = 12, fig.height = 20}
df %>%
  filter(description %in% c("ROBBERY"),
         crimedate>= '2021-01-01') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate),
         crime_month = month(crimedate)) %>%
  count(crime_month, crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_day, crime_hour, fill = pct)) +
  facet_wrap(~crime_month) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_day, crime_hour, label = n)) +
  scale_fill_continuous(type = "viridis") +
  theme_iteam_presentations() +
  ggtitle(paste0("ROBBERIES\nsince ", min(df$crimedate)))
  
```


```{r}
df %>% 
  filter(crimedate >= "2021-01-21",
         crimedate < "2022-01-22",
         description %in% c("HOMICIDE", "SHOOTING")) %>%
  mutate(
    sunrise = getSunlightTimes(
      date = as.Date(crimedate), 
      lat = 39.2904, 
      lon = -76.6122, 
      tz = "America/New_York")$sunrise,
    sunset = getSunlightTimes(
      date = as.Date(crimedate), 
      lat = 39.2904, 
      lon = -76.6122, 
      tz = "America/New_York")$sunset,
    crime_datetime = as.POSIXct(ymd(crimedate) + hms(crimetime),
                                tz = "America/New_York"),
    sunriseNumberWrong = as.numeric(sunrise),
    sunsetNumberWrong = as.numeric(sunset),
    crimeNumberWrong = as.numeric(crime_datetime),  
    sunrise = as.POSIXct(sunrise),
    sunset = as.POSIXct(sunset),
    risehourmin = format(as.POSIXct(sunrise), format = "%H:%M"),
    sethourmin = format(as.POSIXct(sunset), format = "%H:%M"),
    crimehourmin = format(as.POSIXct(crime_datetime), format = "%H:%M"),
    daylight = interval(sunrise, sunset),
    wrongoldlogic = ifelse(crime_datetime %within% daylight, T, F),
    pastsunrise = ifelse(crimehourmin >  risehourmin, T, F),
    beforesunset = ifelse(crimehourmin <  sethourmin, T, F),
    during_daylight =ifelse(pastsunrise == T & beforesunset == T, T, F))%>%
  count(district, hour, during_daylight) %>%
  group_by(district, hour) %>%
  mutate(pct_in_daylight = n / sum(n)) %>%
  filter(during_daylight == T) %>%
  select(-during_daylight)
```
```{r DISTRICT, fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("ROBBERY"),
         crimedate >= '2021-01-01',
         district == 'Central') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("CENTRAL ROBBERIES\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate))) 
```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate < '2022-04-24',
         crimedate >= '2021-01-01',
         district == 'Northwestern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("NORTHWESTERN HOMICIDES + SHOOTINGS\n2021-01-01 to 2021-04-23")) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData 2021-01-01 to 2021-04-23"))

```

```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate >= '2021-01-01',
         district == 'Northwestern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("NORTHEASTERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01',
         district == 'Northern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("NORTHERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01',
         district == 'Northwestern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("NORTHWESTERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01',
         district == 'Southeastern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("SOUTHEASTERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01',
         district == 'Southern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("SOUTHERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01',
         district == 'Southwestern') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("SOUTHWESTERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```
```{r fig.height=4, fig.width=8}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01',
         district == 'Western') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate)) %>%
  group_by(crimedate, crimetime) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  count(crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_hour, crime_day, fill = pct)) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_hour, crime_day, label = n), size = 3) +
  scale_fill_continuous(type = "viridis",
                        labels = percent,
                        name = "% of Daily Events") +
  scale_y_reverse(breaks = seq(1,7,1)) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme_iteam_google_docs() +
  ggtitle(paste0("WESTERN HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate))) +
    labs(
       x = "Hour of Day",
       y = "Day of Week (1 = Sunday)",
       caption = paste0("Part1 Crime\nData ", min(df$crimedate), " to ", max(df$crimedate)))

```

```{r fig.width = 12, fig.height = 20}
df %>%
  filter(description %in% c("HOMICIDE", "SHOOTING"),
         crimedate>= '2021-01-01') %>%
  mutate(crimetime = hms::as_hms(crimetime),
         crime_hour = hour(crimetime),
         crime_day = wday(crimedate),
         crime_month = month(crimedate)) %>%
  count(district, crime_day, crime_hour) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(crime_day, crime_hour, fill = pct)) +
  facet_wrap(~district) +
  geom_tile(color = "white", ) +
  geom_text(aes(crime_day, crime_hour, label = n)) +
  scale_fill_continuous(type = "viridis") +
  theme_iteam_presentations() +
  ggtitle(paste0("HOMICIDES + SHOOTINGS\nsince ", min(df$crimedate)))
  
```


